# Generated by Django 2.2.28 on 2026-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemypet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
