# Generated by Django 2.2.28 on 2026-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemypet', '0002_auto_20260310_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
